<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Direct Request</name>
   <tag></tag>
   <elementGuidId>f02df2e0-1493-4aa1-b518-cbe13fa683fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='user-form']/form/div/div[6]/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>545b7ac5-8300-4aae-944a-0f7ea5615c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://deliverinhour.com/view_direct_request</value>
      <webElementGuid>958df33c-e6db-4772-836a-b0e7f0c9a925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
      <webElementGuid>78a80f01-91e6-407b-92d0-a155dff15616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Direct Request</value>
      <webElementGuid>5ef3a0a8-65e1-4c9f-a9ba-d171ce08836d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-form&quot;)/form[1]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row set-center&quot;]/div[@class=&quot;col-lg-6 col-md-9 col-sm-8 col-xs-3&quot;]/div[1]/div[@class=&quot;request-p1&quot;]/a[@class=&quot;text-center&quot;]</value>
      <webElementGuid>ca2c9ad0-564b-4b1e-9cba-652e8735db41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-form']/form/div/div[6]/div/div/div/a</value>
      <webElementGuid>299a11b9-d87d-4fbb-a80a-37e69088d3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Direct Request')]</value>
      <webElementGuid>e3390aa3-6745-4b75-b202-e404b36f05ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saved Plan'])[1]/following::a[1]</value>
      <webElementGuid>6e41b8d6-cf76-4d36-9bca-6457fa3b2c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request History'])[1]/following::a[2]</value>
      <webElementGuid>eddce6a9-3096-497b-9d66-a631ce0d3d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Profile Info'])[1]/preceding::a[1]</value>
      <webElementGuid>178af2c6-630a-493a-afb1-801c08c9c3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Direct Request']/parent::*</value>
      <webElementGuid>e6e77eeb-4d02-4fd2-81c3-1330d86d0183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://deliverinhour.com/view_direct_request')]</value>
      <webElementGuid>dac05584-17a9-4850-959b-f64d3cf0cc25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/a</value>
      <webElementGuid>e7283be5-df03-42ab-844d-175847b5eb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://deliverinhour.com/view_direct_request' and (text() = 'Direct Request' or . = 'Direct Request')]</value>
      <webElementGuid>9aa816aa-3043-4192-bd8a-84788207815c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
