<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>e555a4d8-8af1-4667-80a0-e58839867f59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//header[@id='header']/div[2]/div/a[2])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>265a59a1-b0a4-4730-bf5c-841312090740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://deliverinhour.com/signin</value>
      <webElementGuid>6e9bc634-2c84-4f0b-be8f-2c952b3788b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>index-footer btn btn-md waves-effect waves-light</value>
      <webElementGuid>852e038c-5d53-4bb8-87d4-3c8c9834267b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>69faf28c-142f-46b6-a78b-13e8d76b0e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fsModal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header d-none d-md-inline-block&quot;]/header[@id=&quot;header&quot;]/div[@class=&quot;pull-right btn-responsive m-3&quot;]/div[@class=&quot;pull-right&quot;]/a[@class=&quot;index-footer btn btn-md waves-effect waves-light&quot;]</value>
      <webElementGuid>067aea53-315c-4b80-b6ce-d8e2c47183d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//header[@id='header']/div[2]/div/a[2])[2]</value>
      <webElementGuid>2bee48d4-90f5-42a4-aaee-965cd4a3e7db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Login')])[2]</value>
      <webElementGuid>c648cbab-2936-49bf-a606-da1636959c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[2]/following::a[1]</value>
      <webElementGuid>07f32a87-3d94-4468-a11e-a0ce60a6794c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[2]/following::a[2]</value>
      <webElementGuid>9b01273e-d00f-491d-b633-9b4363f64b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[2]/preceding::a[1]</value>
      <webElementGuid>fee8f49e-60f3-4814-8195-483fff4193ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[1]/preceding::a[13]</value>
      <webElementGuid>0f98d8c0-cdf9-430e-a320-f18bf7c5e812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://deliverinhour.com/signin')])[2]</value>
      <webElementGuid>9e5fe6d3-6bea-4291-b571-5dadb9bd4660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/header/div[2]/div/a[2]</value>
      <webElementGuid>bc480c70-2e33-4a67-a4da-e47d7788e821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://deliverinhour.com/signin' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>a2af5258-d912-48c5-9671-1a1b262b0f38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
