<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>ec79e1e1-dd24-459f-9745-08bd67ef04d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//header[@id='header']/div[2]/div/a[2])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a8b6fcad-e158-4d15-94b1-7f0f8e77c514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://deliverinhour.com/signin</value>
      <webElementGuid>da3cb22a-8741-4131-b858-1edefd899199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>index-footer btn btn-md waves-effect waves-light</value>
      <webElementGuid>97980f05-7154-4661-99dd-020d3e9762f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>595b01fc-3355-4281-8314-b078f1bc7c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fsModal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header d-none d-md-inline-block&quot;]/header[@id=&quot;header&quot;]/div[@class=&quot;pull-right btn-responsive m-3&quot;]/div[@class=&quot;pull-right&quot;]/a[@class=&quot;index-footer btn btn-md waves-effect waves-light&quot;]</value>
      <webElementGuid>73409260-1fc2-433c-8c1d-8223a92d3b63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//header[@id='header']/div[2]/div/a[2])[2]</value>
      <webElementGuid>ce30a306-7f32-4198-b9f4-8ee482294663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Login')])[2]</value>
      <webElementGuid>a62cc3aa-ddc5-4f81-addc-36099615b820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[2]/following::a[1]</value>
      <webElementGuid>8dd5e695-fa94-4ab8-9e14-af71aa994428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[2]/following::a[2]</value>
      <webElementGuid>75d4d146-807f-4db9-a3c2-534628ccda46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[2]/preceding::a[1]</value>
      <webElementGuid>7121b61b-9557-4b75-88cf-8c7acfccc8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[1]/preceding::a[13]</value>
      <webElementGuid>1eabd0c5-68d8-4e9e-9a23-8ae58e6e5c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://deliverinhour.com/signin')])[2]</value>
      <webElementGuid>aee1c2c3-2ba7-4382-ade1-a0584a3c7425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/header/div[2]/div/a[2]</value>
      <webElementGuid>9714c3b9-2e88-4c7c-ac30-668f829dd9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://deliverinhour.com/signin' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>d415b646-51c2-4541-8846-fbf85b175fe8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
