<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New Request</name>
   <tag></tag>
   <elementGuidId>f7cb63ce-6867-4647-9551-41cef52eeadb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='user-form']/form/div/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.text-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>89cd4c82-48c9-48c9-81d2-c105710471fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://deliverinhour.com/new_request</value>
      <webElementGuid>30d0a1b1-6f8e-47b6-a486-b112655058e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
      <webElementGuid>2a88cb45-b858-4205-84e3-f0557f52bda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Request</value>
      <webElementGuid>739c68bf-f796-49a1-87e8-8a65b45f3efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-form&quot;)/form[1]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row set-center&quot;]/div[@class=&quot;col-lg-6 col-md-9 col-sm-8 col-xs-3&quot;]/div[1]/div[@class=&quot;request-p1&quot;]/a[@class=&quot;text-center&quot;]</value>
      <webElementGuid>b7a1bcf1-7373-4ffc-a854-0e8bff7f6cc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-form']/form/div/div/div/div/div/a</value>
      <webElementGuid>66ff1484-4f26-4ff5-8f54-9793ab346e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'New Request')]</value>
      <webElementGuid>4c5b55c4-ee52-4a4f-97c0-c911712fc702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sergiy Prygara'])[1]/following::a[1]</value>
      <webElementGuid>067651ac-f3b9-4de4-923a-caf3fca58cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay For Delivery'])[1]/preceding::a[1]</value>
      <webElementGuid>42561af6-f732-4c53-9f2d-079527fe915b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request List'])[1]/preceding::a[2]</value>
      <webElementGuid>f835a325-8c44-43ec-971e-38e6955c86c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New Request']/parent::*</value>
      <webElementGuid>3bca0763-2fc8-40ef-899b-8dd068719445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://deliverinhour.com/new_request')]</value>
      <webElementGuid>669dfe36-b1c1-4f94-a2f4-0ad970be9d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>5babb6d6-0716-4e95-9c65-5a28e5bc3e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://deliverinhour.com/new_request' and (text() = 'New Request' or . = 'New Request')]</value>
      <webElementGuid>b39df758-a8b6-40cc-90f0-e8640ea4babf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
