<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>7cc01d30-7bfd-4721-9dca-65bc956452b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//header[@id='header']/div[2]/div/a[2])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>43f1f0fe-d355-4ccb-ac3d-12c5e05edb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://deliverinhour.com/signin</value>
      <webElementGuid>05447146-6d07-4962-baea-fe5a6453ef78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>index-footer btn btn-md waves-effect waves-light</value>
      <webElementGuid>939969af-eaeb-49af-b884-c0e5446180e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>4c35dd0f-3341-4a65-bb58-93788cbf5250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fsModal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header d-none d-md-inline-block&quot;]/header[@id=&quot;header&quot;]/div[@class=&quot;pull-right btn-responsive m-3&quot;]/div[@class=&quot;pull-right&quot;]/a[@class=&quot;index-footer btn btn-md waves-effect waves-light&quot;]</value>
      <webElementGuid>fbf9b29b-ebe5-4b95-bd1d-98281d0935d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//header[@id='header']/div[2]/div/a[2])[2]</value>
      <webElementGuid>c57ad0bd-127f-4b2e-bc0e-9d3f0255686a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Login')])[2]</value>
      <webElementGuid>d3e58c8a-0da7-47d2-bf38-7b3525237551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[2]/following::a[1]</value>
      <webElementGuid>265f6acf-39f5-4749-a054-5006606fec2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[2]/following::a[2]</value>
      <webElementGuid>ff003595-83c0-4fe4-bc76-7676e7702199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[2]/preceding::a[1]</value>
      <webElementGuid>de263f5f-d7b0-4ad5-8188-1df59a083718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[1]/preceding::a[13]</value>
      <webElementGuid>446b38ca-42d8-4a2b-9fca-82d331d619eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://deliverinhour.com/signin')])[2]</value>
      <webElementGuid>1a21b241-3604-4d1f-8331-e7b0ffad7abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/header/div[2]/div/a[2]</value>
      <webElementGuid>7420d1e4-2ac3-4844-8f0a-82f5bdbf8ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://deliverinhour.com/signin' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>d9610cce-41af-44b2-8756-c5c482dfa24d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
